resolver: lts-12.22
allow-newer: true
packages:
- .
extra-deps:
# - base-noprelude-4.10.1.0
- liquid-fixpoint-0.7.0.7
- located-base-0.1.1.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
# - git: https://github.com/regen-network/haskell-abci.git
#   commit: 07d4f7f8ff2eae2c74f4c943a61ed4dbdf99da54
- network-conduit-1.1.0
- proto-lens-protoc-0.2.2.3
- haskell-src-exts-1.19.1
- process-1.4.3.0
- simple-smt-0.7.1
nix:
  # enable: true
  packages: [z3, zlib, protobuf, haskellPackages.happy]
